runtime: nodejs20  # ใช้ Node.js เวอร์ชันล่าสุดที่รองรับ
env: standard

instance_class: F1  # สามารถปรับขนาดตามความต้องการ

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  DB_HOST: /cloudsql/chonsom-api:asia-southeast1:chomsom
  DB_USER: admin
  DB_PASSWORD: 411
  DB_NAME: chomsom
  DB_PORT: 3306
